# Generated by Django 5.2 on 2025-04-21 11:31

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_img_text_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='/images'),
        ),
        migrations.AlterField(
            model_name='img',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
