# Generated by Django 5.2 on 2025-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_img_image_url_alter_img_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
