# Generated by Django 5.2 on 2025-04-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_img_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
