# Generated by Django 5.2 on 2025-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
